-- AlterTable
ALTER TABLE "Lead" ALTER COLUMN "score" DROP NOT NULL;
ALTER TABLE "Lead" ALTER COLUMN "tier" DROP NOT NULL;
ALTER TABLE "Lead" ALTER COLUMN "reasoning" DROP NOT NULL;
ALTER TABLE "Lead" ALTER COLUMN "draftReply" DROP NOT NULL;
ALTER TABLE "Lead" ALTER COLUMN "keySignals" SET DEFAULT ARRAY[]::TEXT[];
